# Generated by Django 2.2.3 on 2020-04-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemonentity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='lan',
            new_name='lat',
        ),
    ]
